/*
 * +----------------------------------------------------------+
 * | libgetter - part of Getter Package Manager               |
 * | Licensed under the GNU GPLv3 License. See LICENSE.txt    |
 * |                                                          |
 * | Copyright (C) 2021 dotandl                               |
 * +----------------------------------------------------------+
 */

#include <getter/script/runners/cmd.h>
#include <gtest/gtest.h>

#include <regex>
#include <string>
#include <vector>

using std::regex;
using std::regex_replace;
using std::string;
using std::stringstream;
using std::vector;
using testing::internal::CaptureStdout;
using testing::internal::GetCapturedStdout;

TEST(ShScriptRunner, RunsPrepareFunc) {
  CaptureStdout();

  int err =
      cmd_sr.prepare(GTT_TESTS_DIR "/script/GetterScript.cmd", GTT_TESTS_DIR);

  stringstream stdout_stream(GetCapturedStdout());
  string line;
  vector<string> lines;

  while (getline(stdout_stream, line)) {
    lines.push_back(line);
  }

  // By default, GTT_TESTS_DIR constant, generated by CMake, uses Unix slashes
  // (/). `cd` command on Windows returns the CWD using DOS/Windows slashes (\)
  // so we need to do a conversion.
  const string GTT_TESTS_DIR_WINSLASH =
      regex_replace(string(GTT_TESTS_DIR), regex("\\/"), "\\");

  EXPECT_EQ(err, 2);
  EXPECT_STREQ(lines[0].c_str(), ":prepare");
  EXPECT_STREQ(lines[1].c_str(), GTT_TESTS_DIR_WINSLASH.c_str());
}
