name: CD - Documentation

on:
  push: { branches: [main] }

env:
  BUILD_TYPE: Release

jobs:
  generate-and-pulish-docs:
    name: Generate & Publish Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with: { submodules: recursive }

      - name: Install required libraries and Doxygen
        run: |
          sudo apt-get update && \
          sudo apt-get install -y libpcre2-dev libzip-dev doxygen

      - name: Configure the CMake project (prepare Doxyfile)
        run: |
          cmake \
          -S ${{github.workspace}} \
          -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Generate Documentation
        run: |
          cmake \
          --build ${{github.workspace}}/build \
          --target libgetter_docs \
          --config ${{env.BUILD_TYPE}}

      - name: Deploy the documentation to Github Pages
        if: ${{ !env.ACT }} # Don't publish when testing locally with `act`
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: ${{github.workspace}}/docs/html
